# Generated by Django 5.0 on 2024-05-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('association_or_hospital', models.CharField(max_length=255)),
                ('date_and_hour', models.DateTimeField()),
            ],
        ),
    ]
