# Generated by Django 5.0 on 2024-05-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_event_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_generated',
            field=models.BooleanField(default=False),
        ),
    ]
