# Generated by Django 5.0.6 on 2024-06-23 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0007_participant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='participants',
            new_name='participants_count',
        ),
    ]
