# Utilisez l'image officielle de Python
FROM python:3.9

# Définir le répertoire de travail dans le conteneur
WORKDIR /backend

# Copier les fichiers de dépendances
COPY requirements.txt .

# Installer les dépendances
RUN pip install -r requirements.txt

# Copier le reste du code de l'application
COPY . .

# Exposer le port utilisé par Django
EXPOSE 8000

# Commande pour démarrer le serveur Django
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
