# Generated by Django 5.0.4 on 2024-05-07 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
