# Generated by Django 5.0.4 on 2024-05-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_alter_blood_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood',
            name='date_donation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
