# Generated by Django 5.0.4 on 2024-06-03 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0006_bloodhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blood',
            name='donor_name',
        ),
    ]
