# Generated by Django 5.0.4 on 2024-06-03 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0007_remove_blood_donor_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloodHistory',
        ),
    ]
